


###
POST http://localhost:8080/api/v1/attach/upload
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0MDI4MDk4MTgxMzk2NmRhMDE4MTM5NjZmMmZmMDAwMCIsImlhdCI6MTY1NTA5MTM5MSwiaXNzIjoibWF6Z2kgcHJvZHVjdGlvbiJ9.3exLP-80JgGoBz5hl24u6JVxqK9n7r4ZQkQNsftcBrQ
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="photo.mp4"

< C:\Users\Admin\Desktop\photo.jpg
--WebAppBoundary--



###
DELETE http://localhost:8080/api/v1/attach/delete/12BxY6gyj44JhvGbjedIitwkXNeqSpBLu

