
###
GET http://localhost:8080/api/v1/profile/drgfkjhlkj
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0MDI4MDk4MTgxMzk2NmRhMDE4MTM5NjZmMmZmMDAwMCIsImlhdCI6MTY1NTA5MTM5MSwiaXNzIjoibWF6Z2kgcHJvZHVjdGlvbiJ9.3exLP-80JgGoBz5hl24u6JVxqK9n7r4ZQkQNsftcBrQ